### ISSUE TITLE
Add a source marker to all created files

### ISSUE THREAD

**Issue by DavidS** [puppetlabs/pdk-templates#142]
From a slack conversation with @GeoffWilliams:

Add a PDK marker to all templates. 

For `_init` files and object templates, it should read `# initially generated with PDK <%= @configs['pdk_version'] %> from <%= @configs['template_source_path'] %>`, for files that get updated on `pdk update`, it should read `# maintained by PDK, from <%= @configs['template_source_path'] %>`. This makes it clear which files can be touched directly, and which will be updated, while at the same time avoiding churn (for "maintained" files, the metadata.json entry shows when it was last updated).

This will need additional changes in the PDK to provide the `pdk_version`, and `template_source_path` values.

**Comment by rtib** [comment]
The whole content of `metadata.json`, including `pdk_version`, `template-url` and `template-ref` is available within `@configs['module_metadata']`, thus there is no need to change PDK to add such comments via templates.

For file which PDK is creating initially but not maintaining them after, i.e. `_init` files and object templates, such a comment is mostly decorative.

Managed files may go unmanaged eventually, by declaring them `unmanaged: true` in `.sync.yml`. A "managed by PDK" comment would not be removed, since the file is not managed anymore, so the remaining comment is only misleading.

Also consider, we have many files of different types managed by PDK, e.g. many YAML files, Ruby-scripts, .gitignore, .yardopts, .puppet-lint.rc, etc. which may have different comment syntax.

The metadata.json file is a very special case, which is managed by PDK (but not through a template within pdk-templates), though many fields can be edited manually.

For some files it simply does not make sense, e.g. CHANGELOG.md, README.md

Probably, a specific subcommand could be introduced to PDK which lists all managed files or it may be queried if a specific file is managed.

**Comment by DavidS** [comment]
Given @rtib's excellent commentary, I'll close this `wontfix`
