### ISSUE TITLE
CI templates need a way to specify how to always ignore the includes from pdk-templates

### ISSUE THREAD

**Issue by ghoneycutt** [puppetlabs/pdk-templates#226]
pdk-templates allows you to specify `remove_includes` though you have to see what the current ones are and copy/paste those. This is very brittle as the entries in the pdk-templates will change over time. A boolean that would allow you to always ignore the includes from pdk-templates would be useful.

**Comment by rtib** [comment]
Principally the `remove_includes` is not needed at all, since the deep_merge function incorporates the knockout_prefix. The usage is barely documented at [Removing default configuration values](https://github.com/puppetlabs/pdk-templates#removing-default-configuration-values) and does need deep understanding of how deep_merge is working. Probably this is just a lack of documentation.

You can knockout to merge the whole`includes` array by adding the following to your `.sync.yml`:
```
.travis.yml:
  includes: ['---']
```

This will lead to have an empty array in `includes` and the `.travis.yml` template will only add jobs defined within `extras`.

**Comment by DavidS** [comment]
As reported in #132, the same ergonomics issue is also present in appveyor config.

**Comment by david22swan** [comment]
Hey, thank you for brining this to our attention, however as part of the process of cleaning up our older issues and getting on top of our backlog, we our now closing out older issues that have not been active within the last few years.
If you feel that this is still a significant issue please feel free to reopen this and ping us directly.
