### ISSUE TITLE
Style/TrailingCommaInLiteral is deprecated

### ISSUE THREAD

**Issue by towo** [puppetlabs/pdk-templates#242]
Current Rubocop has split `Style/TrailingCommaInLiteral` to `Style/TrailingCommaInArrayLiteral` and `Style/TrailingCommaInHashLiteral`.

https://github.com/puppetlabs/pdk-templates/blob/f778803b15dfb58a318977ac61644ee9fffcd5ce/config_defaults.yml#L184

**Comment by rodjek** [comment]
Hi @towo, PDK currently locks rubocop at 0.49.x in order to provide consistent behaviour across our range of supported Ruby versions. The `Style/TrailingCommaInLiteral` check was not split up until rubocop 0.53.0, so we can not change the default configuration at this time.

If you have upgraded rubocop in your module(s) and wish to remove that cop from the generated config, you can do this by adding the following segment to your `.sync.yml` and running `pdk update`.

```yaml
.rubocop.yml:
  default_configs:
    Style/TrailingCommaInLiteral: '---'
```

**Comment by Felixoid** [comment]
Hello @rodjek 

It's already 1 year since issue was created, and there's already two deprecations in the .rubocop.yml

```Error: The `Layout/IndentHeredoc` cop has been renamed to `Layout/HeredocIndentation`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Style/TrailingCommaInLiteral` cop has been removed. Please use `Style/TrailingCommaInArrayLiteral` and/or `Style/TrailingCommaInHashLiteral` instead.
(obsolete configuration found in .rubocop.yml, please update it)```

I have 2 questions because of that:

1. How could I update rubocop version and still use PDK somehow? The rubocop version is locked in the gem puppet-module-posix-dev-r2.5 and I can't find, how to override it
2. If the answer to the 1st question is "I can't", that means, the pdk bundler will be broken?
